version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: speedwaytyper
      POSTGRES_USER: speedway
      POSTGRES_PASSWORD: speedway
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./Server/Database/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Server/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=speedwaytyper;Username=speedway;Password=speedway
      Jwt__Key: YourVeryLongAndSecureKeyHereWithAtLeast32Characters
      Jwt__Issuer: SpeedwayTyperApp
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data:
